INSERT INTO public.rol (codigo, nombre, descripcion) VALUES ('001', 'administrador', 'Permite ingresar nuevos lugares turísticos');
INSERT INTO public.rol (codigo, nombre, descripcion) VALUES ('002', 'usuario', 'Permite visualizar lugares turisticos y buscarlos');


INSERT INTO public."tipo-discapacidad" (id, nombre) VALUES (1, 'Física');
INSERT INTO public."tipo-discapacidad" (id, nombre) VALUES (2, 'Auditiva');
INSERT INTO public."tipo-discapacidad" (id, nombre) VALUES (3, 'Visual');
INSERT INTO public."tipo-discapacidad" (id, nombre) VALUES (4, 'Ninguna');
INSERT INTO public."tipo-discapacidad" (id, nombre) VALUES (5, 'Fisica y Auditiva');
INSERT INTO public."tipo-discapacidad" (id, nombre) VALUES (6, 'Auditiva y Visual');
INSERT INTO public."tipo-discapacidad" (id, nombre) VALUES (7, 'Fisica y Visual');
INSERT INTO public."tipo-discapacidad" (id, nombre) VALUES (8, 'Fisica, Auditiva y Visual');


INSERT INTO public."tipo-lugar-turistico" (id, nombre) VALUES (1, 'Iglesia');
INSERT INTO public."tipo-lugar-turistico" (id, nombre) VALUES (2, 'Museo');
INSERT INTO public."tipo-lugar-turistico" (id, nombre) VALUES (3, 'Plaza');
INSERT INTO public."tipo-lugar-turistico" (id, nombre) VALUES (4, 'Restaurante');
INSERT INTO public."tipo-lugar-turistico" (id, nombre) VALUES (5, 'Hotel');
INSERT INTO public."tipo-lugar-turistico" (id, nombre) VALUES (6, 'Atractivo Turístico');
INSERT INTO public."tipo-lugar-turistico" (id, nombre) VALUES (7, 'Teatro');


INSERT INTO public."lugar-turistico" (id, nombre, "descripcionLugar", precio, horario, "descripcionAccesibilidad", valoracion, latitud, longitud, foto_lugar, "tipoLugar", "tipoDiscapacidad") VALUES (1, 'Monasterio de Santa Catalina de Siena', 'En la esquina de las calles Flores y Espejo se encuentra el llamativo Monasterio de Santa Catalina, que cuenta con un museo que destaca recuerdos religiosos y mas de 100 lienzos de arte barroco', 'N/A', 'Lunes a Viernes 09h00 a 17h00', 'N/A', '1', -0.221639, -78.510559000000001, 'santa-catalina-quito.jpg', 1, 4);
INSERT INTO public."lugar-turistico" (id, nombre, "descripcionLugar", precio, horario, "descripcionAccesibilidad", valoracion, latitud, longitud, foto_lugar, "tipoLugar", "tipoDiscapacidad") VALUES (2, 'Iglesia de San Agustin', 'Se encuentra en Quito en la parroquia González Suárez entre las calles Guayaquil. Chile y Flores.', 'N/A', 'Lunes a viernes: 09:00 - 12:30 y 14:00 - 17:00. sábado: 09:00 - 13:00', 'N/A', '1', -0.220273, -78.510358999999994, 'sanAgustin.jpg', 1, 4);
INSERT INTO public."lugar-turistico" (id, nombre, "descripcionLugar", precio, horario, "descripcionAccesibilidad", valoracion, latitud, longitud, foto_lugar, "tipoLugar", "tipoDiscapacidad") VALUES (3, 'Café el Fraile', 'Café del Fraile. sitio ubicado en La Plaza de la Independencia. Centro Histórico de Quito. inaugurado el 15 de mayo de 2002. en el Palacio Arzobispal.', 'N/A', 'Lunes – Viernes: 9am – 11pm y Domingo: 10am – 9pm', 'N/A', '1', -0.21959699999999999, -78.511798999999996, 'elFraile.jpg', 4, 4);
INSERT INTO public."lugar-turistico" (id, nombre, "descripcionLugar", precio, horario, "descripcionAccesibilidad", valoracion, latitud, longitud, foto_lugar, "tipoLugar", "tipoDiscapacidad") VALUES (4, 'Heladeria restaurante San Agustin', 'Situada en la calle Guayaquil N5-59 y Mejia. la Heladería San Agustín es un restaurante que ha servido comida típica a los quiteños por casi 150 años.', 'N/A', 'Restaurante Lun - Dom : 10am - 3:30pm y Heladería-Cafetería Lun - Vie : 10am - 5:30pm', 'N/A', '1', -0.22004599999999999, -78.510397999999995, 'heladeriaSanAgustin.png', 4, 4);
INSERT INTO public."lugar-turistico" (id, nombre, "descripcionLugar", precio, horario, "descripcionAccesibilidad", valoracion, latitud, longitud, foto_lugar, "tipoLugar", "tipoDiscapacidad") VALUES (5, 'Palacio de Carondelet', 'El Palacio de Carondelet es la sede del Gobierno y residencia oficial del Presidente de la República del Ecuador', 'Gratuita. es necesario presentar una identificación (Cédula de Identidad o Pasaporte)', 'De martes a viernes de 9h00 a 19h00 y los días lunes de 15h00 a 19h00. Los sábados va de 9h00 a 22:00 y el domingo 09h00 16h00', 'El ingreso cuenta con una rampa de madera. El siguiente paso es el filtro de seguridad. que no es posible pasar con una silla ancha. pero existe una puerta alterna cerca. Al ingresar a los patios interiores se puede transitar con facilidad y el guía se encarga de pedir el ascensor para llegar a la segunda planta', '1', -0.21968599999999999, -78.512692999999999, 'palacio.jpg', 6, 1);
INSERT INTO public."lugar-turistico" (id, nombre, "descripcionLugar", precio, horario, "descripcionAccesibilidad", valoracion, latitud, longitud, foto_lugar, "tipoLugar", "tipoDiscapacidad") VALUES (7, 'Hotel Plaza Grande', 'Fue  la primera casa construida durante  la fundación de la ciudad en el siglo XVI.   posteriormente fue habitada por las familias más pudientes y reconocidas de la ciudad. A comienzos del siglo XX. fue el primer hotel de lujo de la ciudad.', 'N/A', 'N/A', 'Es accesible porque cuenta con 1 habitación adaptada y espacios amplios para la movilización del huésped con discapacidad.', '1', -0.21942800000000001, -78.512066000000004, 'hotel-plaza-grande.jpg', 5, 1);
INSERT INTO public."lugar-turistico" (id, nombre, "descripcionLugar", precio, horario, "descripcionAccesibilidad", valoracion, latitud, longitud, foto_lugar, "tipoLugar", "tipoDiscapacidad") VALUES (8, 'Iglesia de la Inmaculada Concepción', 'García Moreno N10-43. Quito 170401', 'N/A', ' Lunes a sábado 07:30 – 12:00 y 14:30 – 16:00', 'N/A', '1', -0.21929999999999999, -78.512153999999995, 'inmaculada.jpg', 1, 4);
INSERT INTO public."lugar-turistico" (id, nombre, "descripcionLugar", precio, horario, "descripcionAccesibilidad", valoracion, latitud, longitud, foto_lugar, "tipoLugar", "tipoDiscapacidad") VALUES (9, 'Vista Hermosa Centro Historico', 'Calle Mejía. 4 53. Quito 170401', 'N/A', 'Lunes a Sábado de 13:00 a 24:00 y Domingo de 12:00 a 20:00 ', 'N/A', '1', -0.21912699999999999, -78.511431999999999, 'vistaHermosa.jpg', 1, 4);
INSERT INTO public."lugar-turistico" (id, nombre, "descripcionLugar", precio, horario, "descripcionAccesibilidad", valoracion, latitud, longitud, foto_lugar, "tipoLugar", "tipoDiscapacidad") VALUES (10, 'Hotel Patio Andaluz ', 'Garcia Moreno N6-52 entre Mejia y. José Joaquín Olmedo. Quito 170401', 'N/A', 'N/A', 'N/A', '1', -0.21848200000000001, -78.511312000000004, 'patioAndaluz.jpg', 5, 4);
INSERT INTO public."lugar-turistico" (id, nombre, "descripcionLugar", precio, horario, "descripcionAccesibilidad", valoracion, latitud, longitud, foto_lugar, "tipoLugar", "tipoDiscapacidad") VALUES (11, 'Hotel el Relicario del Carmen', 'Venezuela & José Joaquín Olmedo. Olmedo 1041. Quito 170150', 'N/A', 'N/A', 'N/A', '1', -0.21893599999999999, -78.510732000000004, 'relicario.jpg', 5, 4);
INSERT INTO public."lugar-turistico" (id, nombre, "descripcionLugar", precio, horario, "descripcionAccesibilidad", valoracion, latitud, longitud, foto_lugar, "tipoLugar", "tipoDiscapacidad") VALUES (12, 'El Carmen Bajo', 'Jose Olmedo y Venzuela ', 'Gratuito', 'N/A', 'N/A', '1', -0.21842700000000001, -78.510171, 'carmenBajo.jpg', 1, 4);
INSERT INTO public."lugar-turistico" (id, nombre, "descripcionLugar", precio, horario, "descripcionAccesibilidad", valoracion, latitud, longitud, foto_lugar, "tipoLugar", "tipoDiscapacidad") VALUES (13, 'Teatro Sucre', 'Guayaquil &. Manabi. Quito 170401', 'N/A', 'N/A', 'N/A', '1', -0.219164, -78.508864000000003, 'teatroSucre.jpg', 7, 1);
INSERT INTO public."lugar-turistico" (id, nombre, "descripcionLugar", precio, horario, "descripcionAccesibilidad", valoracion, latitud, longitud, foto_lugar, "tipoLugar", "tipoDiscapacidad") VALUES (14, 'Teatro Bolivar ', 'Guyaquil y Espejo', 'N/A', 'La oficina del Teatro Bolívar está abierta al público de lunes a viernes desde las 9h00 hasta las 17h30', 'N/A', '1', -0.22154399999999999, -78.511138000000003, 'teatroBolivar.jpg', 7, 4);
INSERT INTO public."lugar-turistico" (id, nombre, "descripcionLugar", precio, horario, "descripcionAccesibilidad", valoracion, latitud, longitud, foto_lugar, "tipoLugar", "tipoDiscapacidad") VALUES (15, 'Dulceria colonial ', 'Venezuela y Espejo', 'N/A', 'Lunes a Viernes 7H00-19H30 Sábado y Domingo 7H00-22H30', 'N/A', '1', -0.22054799999999999, -78.512266999999994, 'dulceriaColonial.jpg', 6, 4);
INSERT INTO public."lugar-turistico" (id, nombre, "descripcionLugar", precio, horario, "descripcionAccesibilidad", valoracion, latitud, longitud, foto_lugar, "tipoLugar", "tipoDiscapacidad") VALUES (16, 'Catedral Metropolitana de Quito', 'La Catedral Primada de Quito. es una de las iglesias más importantes de la ciudad. su historia se remonta al año de 1535. cuando luego de la fundación española de Quito', 'Turista Nacional (2.00 usd Adultos. 1.00 usd Niños. estudiantes. adultos mayores. personas con discapacidad). Visita a Cúpulas (Iglesia + Museo + Cúpulas) (4.00 usd por persona. Turista Extranjero. 3.00 usd Adultos. 2.00 usd Niños. estudiantes. adultos. mayores. personas con discapacidad. Visita a Cúpulas (Iglesia + Museo + Cúpulas) (6.00 usd por persona)', 'Lunes a sábado: de 09:30 a 17:00', 'N/A', '1', -0.220472, -78.512539000000004, 'catedralMetropolitana.jpg', 1, 4);
INSERT INTO public."lugar-turistico" (id, nombre, "descripcionLugar", precio, horario, "descripcionAccesibilidad", valoracion, latitud, longitud, foto_lugar, "tipoLugar", "tipoDiscapacidad") VALUES (17, 'Iglesia del Sagrario', 'El Sagrario es la capilla sacramental de la Catedral Primada de Quito. a la cual está anexa. Su construcción se realiza entre los siglos XVII y XVIII. los trabajos de cimentación inician gracias a la Cofradía del Sagrado Sacramento en el año 1617 por el Sacerdote Jesuita Marcos Guerra. ', 'N/A', 'Horario de Misa:Lunes a viernes: 08:00 - 10:00 - 12:00 - 17:00.  Sábado: 08:00 - 10:00 - 12:00. Domingo: 08:00 - 09:00 - 10:00 - 11:00 - 12:00 - 17:00', 'N/A', '3', -0.220613, -78.512744999999995, 'elSagrario.jpg', 1, 4);
INSERT INTO public."lugar-turistico" (id, nombre, "descripcionLugar", precio, horario, "descripcionAccesibilidad", valoracion, latitud, longitud, foto_lugar, "tipoLugar", "tipoDiscapacidad") VALUES (18, 'Museo Alberto Mena Caamaño', 'El “Museo de Arte e Historia Alberto Mena Caamaño” fue creado el 28 de mayo de 1957 a partir del fondo donado por Alberto Mena Caamaño. En 1970 el museo integró a la exposición permanente una sala sobre la masacre del 2 de Agosto de 1810. ', 'Adulto 1.50. Estudiante: colegio y universidad 0.75. Niños. discapacitados y 3ra edad 0.50', 'Martes a sábado: 9:00 a 17:30. Domingo: 10:00 a 16:00', 'Rampa de acceso adecuada para personas en silla de ruedas', '5', -0.21984000000000001, -78.513237000000004, 'museoMenaC.png', 2, 1);
INSERT INTO public."lugar-turistico" (id, nombre, "descripcionLugar", precio, horario, "descripcionAccesibilidad", valoracion, latitud, longitud, foto_lugar, "tipoLugar", "tipoDiscapacidad") VALUES (19, 'Museo de la Ciudad', 'El Museo de la Ciudad se inauguró el 23 de julio de 1998 en las instalaciones que desde 1565 hasta 1974 fueron el Antiguo Hospital San Juan de Dios. Rehabilitada por la Empresa del Centro Histórico y el FONSAL durante un periodo de cuatro años. esta edificación constituye uno de los mayores bienes patrimoniales que conserva la capital.', 'Adulto 3.00. Estudiantes establecimientos municipales 1.00. Estudiantes con Carnét (+12 años) 2.00. Recorrido en inglés 4.00. Niños (3 a 11 años) y Tercera edad (+65) 1.50. Capacidades especiales y Centros de Rehabilitación Libre', '"Martes a domingo: 09:00 a 17:00. último Ingreso 16h00"', 'N/A', '5', -0.222826, -78.515021000000004, 'museoCiudad.jpg', 2, 4);
INSERT INTO public."lugar-turistico" (id, nombre, "descripcionLugar", precio, horario, "descripcionAccesibilidad", valoracion, latitud, longitud, foto_lugar, "tipoLugar", "tipoDiscapacidad") VALUES (20, 'Convento San Francisco:Museo Fray Pedro Gocial', 'Museo de Arte Religioso perteneciente a la Orden de Frailes Menores del Ecuador. Se exhibe en exposición permanente lienzos y esculturas de los siglos XVII – XVIII – XIX de la llamada Escuela Quiteña. Seis salas de exposición. dos galerías. el Claustro más grande de América y para finalizar el Coro de la Iglesia. constituyen los sitios que este museo reserva para sus visitantes.', 'Adulto Nacional o Extranjero 3.00. Niños 1.00. Estudiantes con carnét y Tercera Edad 2.00', '"Lunes a sabado: 09:00 a 17:00. Domingos: 09:00 a 13:00"', 'N/A', '1', -0.220169, -78.514849999999996, 'museoConvento.jpeg', 2, 4);
INSERT INTO public."lugar-turistico" (id, nombre, "descripcionLugar", precio, horario, "descripcionAccesibilidad", valoracion, latitud, longitud, foto_lugar, "tipoLugar", "tipoDiscapacidad") VALUES (21, 'Museo Casa Sucre', '"En la Casa de Sucre se presenta una museografía que relata la vida de Sucre en un contexto humano y social. El lugar guarda los objetos personales y enseres del Mariscal de Ayacucho y de su esposa Mariana Carcelén. El lugar se divide en dos plantas y un patio central con pileta tradicional de piedra colonial."', 'Entrada Libre', 'Martes a domingo: 09:00 a 16h30', 'N/A', '1', -0.22187000000000001, -78.513233, 'museoSucre.jpg', 2, 4);
INSERT INTO public."lugar-turistico" (id, nombre, "descripcionLugar", precio, horario, "descripcionAccesibilidad", valoracion, latitud, longitud, foto_lugar, "tipoLugar", "tipoDiscapacidad") VALUES (22, 'Convento Santo Domingo: Museo Fray Pedro Bedón', 'El Museo fue inaugurado como tal el 6 de noviembre de 1965. siendo Prior el P. Luis Tipan Rojas. aprovechando la madera y tableros del piso del templo. En este momento estamos en la Primera Sala. usted podra? apreciar pinturas y esculturas de los siglos XVII y XVIII en su mayori?a de autores anonimos de la Escuela Quiteña y Europea y de su maximo representante Fray. ', 'Adulto Nacional o Extranjero 3.00. Niño. tercera edad. discapacitados. estudiantes escuelas y colegios 1.00', 'Lunes a Viernes de 9:00 a 13:30 y de 14:30 a 17:00. Sábados 9:00 a 14:00', 'N/A', '1', -0.223633, -78.512038000000004, 'museoFray.jpg', 2, 4);
INSERT INTO public."lugar-turistico" (id, nombre, "descripcionLugar", precio, horario, "descripcionAccesibilidad", valoracion, latitud, longitud, foto_lugar, "tipoLugar", "tipoDiscapacidad") VALUES (23, 'Museo Catedral Primada de Quito', 'El museo presenta una colección de obras de arte de la Escuela Quiteña tanto en pintura como en escultura. cuyos autores fueron los artistas más renombrados de la cuidad colonial. Miguel de Santiago. Caspicara. Manuel de Samaniego. El Padre Carlos. Bernardo Rodríguez. entre otros importantes artistas de los siglos XVII. XVIII. XIX. y XX. ', 'Adulto Extranjero 3.00. Adulto Nacional 2.00. Niños y Tercera edad 1.00. Recorrido de cúpulas 4.00 NAC y 6.00 EXTRANJEROS', 'Lunes a Sàbado: 09:00 a 17:00', 'N/A', '1', -0.22044900000000001, -78.512564999999995, 'museoCatedral.jpg', 2, 4);
INSERT INTO public."lugar-turistico" (id, nombre, "descripcionLugar", precio, horario, "descripcionAccesibilidad", valoracion, latitud, longitud, foto_lugar, "tipoLugar", "tipoDiscapacidad") VALUES (24, 'Museo María Augusta Urrutia', 'La Casa Museo María Augusta Urrutia. que muestra la forma de vida de la aristocracia quiteña en la década de los años 20. del siglo pasado. y además reconoce la labor humanitaria de una mujer que consagró su vida a la obra social.', 'Adulto  2.00. Tercera edad 1.00. Niños hasta 12 años 0.50', 'Martes a viernes: 10:00 a 18:00. Sàbado. domingo y feriados de 09:30 a 17:00', 'N/A', '1', -0.22154199999999999, -78.513908000000001, 'museoMaria.jpg', 2, 4);
INSERT INTO public."lugar-turistico" (id, nombre, "descripcionLugar", precio, horario, "descripcionAccesibilidad", valoracion, latitud, longitud, foto_lugar, "tipoLugar", "tipoDiscapacidad") VALUES (25, 'Museo Manuela Sáenz', 'En un recorrido por el museo se puede conocer la vida de la heroína quiteña entrelazada con los grandes héroes de la independencia. Bolívar y Sucre. Manuelita. considerada como la mujer de América. ella que cabalgó los Andes buscando la libertad de nuestros países', 'Adulto  4.00. Estudiantes. tercera edad 2.00. Niños hasta 12 años 1.00', 'Miércoles a domingo de 10h00 a 17h00', 'N/A', '1', -0.222831, -78.510493999999994, 'museoManuelaSaenz.jpg', 2, 4);
INSERT INTO public."lugar-turistico" (id, nombre, "descripcionLugar", precio, horario, "descripcionAccesibilidad", valoracion, latitud, longitud, foto_lugar, "tipoLugar", "tipoDiscapacidad") VALUES (26, 'Museo de Arte Colonial', 'El guión del Museo gira sobre la Vida y el Arte en el Quito de la época virreinal se analiza la ciudad y sus vivencias en ese período. cuyo eje dinamizador de la sociedad y el arte es la marcada religiosidad de la época. expresada en sus costumbres. devociones y festividades', 'Entrada libre', 'Martes a Sábado: 09:00 a 17:00', 'N/A', '1', -0.21765599999999999, -78.513047999999998, 'museoArteColonial.jpg', 2, 4);
INSERT INTO public."lugar-turistico" (id, nombre, "descripcionLugar", precio, horario, "descripcionAccesibilidad", valoracion, latitud, longitud, foto_lugar, "tipoLugar", "tipoDiscapacidad") VALUES (27, 'Centro Cultural Metropolitano', 'El Centro Cultural Metropolitano es una institución de servicio público adscrita  a la Secretaría de Cultura del Municipio de Quito. cuya  misión  es contribuir al conocimiento. valoración. promoción y disfrute del patrimonio y las diversas  manifestaciones culturales. y a la generación e intercambio de conocimientos.', 'Entrada Libre', '"Martes a Sàbado: 09:00 a 18:00. Domingo: 09:00 a 13:0"', 'N/A', '1', -0.22017400000000001, -78.513144999999994, 'museoMetropolitano.jpg', 2, 4);
INSERT INTO public."lugar-turistico" (id, nombre, "descripcionLugar", precio, horario, "descripcionAccesibilidad", valoracion, latitud, longitud, foto_lugar, "tipoLugar", "tipoDiscapacidad") VALUES (28, 'Museo del Pasillo', 'El Museo – Escuela del Pasillo nace como una propuesta que resalta y reconoce la diversidad cultural. el principio de igual dignidad y respeto para todas las culturas y manifestaciones musicales y abarca una visión general de las músicas del Ecuador. con énfasis en el género musical pasillo.', 'Entrada Libre', 'Martes a domingo de 09h00 a 16h00 ', 'N/A', '1', -0.22193199999999999, -78.514240999999998, 'museoPasillo.jpeg', 2, 4);
INSERT INTO public."lugar-turistico" (id, nombre, "descripcionLugar", precio, horario, "descripcionAccesibilidad", valoracion, latitud, longitud, foto_lugar, "tipoLugar", "tipoDiscapacidad") VALUES (29, 'La Ronda', 'La tradicional calle Morales. más conocida como La Ronda. se la conoce por su importancia histórica y cultural como una de las zonas más emblemáticas de Quito. donde se asentó la llamada “filosofía bohemia” en sus fondas. Músicos. canciones icónicas. grandes bebedores. grandes poetas. surcaron sus aceras. debajo de los pintorescos balcones que siguen intactos hoy. decorados con hermosos geranios. ', 'N/A', 'N/A', 'N/A', '1', -0.22403600000000001, -78.514516, 'laRonda.jpg', 6, 4);
INSERT INTO public."lugar-turistico" (id, nombre, "descripcionLugar", precio, horario, "descripcionAccesibilidad", valoracion, latitud, longitud, foto_lugar, "tipoLugar", "tipoDiscapacidad") VALUES (30, 'La Casa de los Geranios', 'Mantiene la tradición y el sabor de la cocina ecuatoriana. con el apropiado uso de la amplia variedad de ingredientes frescos. aportando nuevas propuestas a la cultura culinaria. con un toque de amor y buen gusto al prepararlos.', 'N/A', 'Lunes a Domingo de 11:00 a 0:00', 'N/A', '1', -0.22502900000000001, -78.513565999999997, 'casaGeranios.jpg', 4, 4);
INSERT INTO public."lugar-turistico" (id, nombre, "descripcionLugar", precio, horario, "descripcionAccesibilidad", valoracion, latitud, longitud, foto_lugar, "tipoLugar", "tipoDiscapacidad") VALUES (31, 'Museo del Carmen Alto', 'El 5 de diciembre del 2013. por primera vez se abren los claustros más antiguos del Monasterio como un museo encargado de mostrar la riqueza del patrimonio cultural. histórico y espiritual carmelita.', '"Adultos 3.00. Estudiantes 2.00. Niños (hasta 12 años) Tercera Edad 1.00"', 'Mièrcoles a Domingo: 09:30 a 16:30', 'N/A', '3', -0.222829, -78.515311999999994, 'museo-carmen-alto-quito.jpg', 2, 4);
